// <auto-generated />
using System;
using ListasCompras.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ListasCompras.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("ListasCompras.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequerModelo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("ListasCompras.Models.ItemListaCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ListaCompraId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ModeloCelularId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ListaCompraId");

                    b.HasIndex("ModeloCelularId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItensListaCompra");
                });

            modelBuilder.Entity("ListasCompras.Models.ListaCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ListasCompra");
                });

            modelBuilder.Entity("ListasCompras.Models.MarcaCelular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MarcasCelular");
                });

            modelBuilder.Entity("ListasCompras.Models.ModeloCelular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarcaCelularId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarcaCelularId");

                    b.ToTable("ModelosCelular");
                });

            modelBuilder.Entity("ListasCompras.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("ListasCompras.Models.ProdutoModeloCompatibilidade", b =>
                {
                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModeloCelularId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProdutoId", "ModeloCelularId");

                    b.HasIndex("ModeloCelularId");

                    b.ToTable("ProdutoModeloCompatibilidades");
                });

            modelBuilder.Entity("ListasCompras.Models.ItemListaCompra", b =>
                {
                    b.HasOne("ListasCompras.Models.ListaCompra", "ListaCompra")
                        .WithMany("Itens")
                        .HasForeignKey("ListaCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ListasCompras.Models.ModeloCelular", "ModeloCelular")
                        .WithMany()
                        .HasForeignKey("ModeloCelularId");

                    b.HasOne("ListasCompras.Models.Produto", "Produto")
                        .WithMany("Itens")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListaCompra");

                    b.Navigation("ModeloCelular");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ListasCompras.Models.ModeloCelular", b =>
                {
                    b.HasOne("ListasCompras.Models.MarcaCelular", "MarcaCelular")
                        .WithMany("Modelos")
                        .HasForeignKey("MarcaCelularId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarcaCelular");
                });

            modelBuilder.Entity("ListasCompras.Models.Produto", b =>
                {
                    b.HasOne("ListasCompras.Models.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ListasCompras.Models.ProdutoModeloCompatibilidade", b =>
                {
                    b.HasOne("ListasCompras.Models.ModeloCelular", "ModeloCelular")
                        .WithMany("Compatibilidades")
                        .HasForeignKey("ModeloCelularId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ListasCompras.Models.Produto", "Produto")
                        .WithMany("Compatibilidades")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModeloCelular");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ListasCompras.Models.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("ListasCompras.Models.ListaCompra", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ListasCompras.Models.MarcaCelular", b =>
                {
                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("ListasCompras.Models.ModeloCelular", b =>
                {
                    b.Navigation("Compatibilidades");
                });

            modelBuilder.Entity("ListasCompras.Models.Produto", b =>
                {
                    b.Navigation("Compatibilidades");

                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
